services:
  ros2:
    image: automation_ws_ros2:latest
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1    
      - QT_DEBUG_PLUGINS=1
      - XAUTHORITY=/tmp/.docker.xauth  
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix